// src/app/guess-form/guess-form.component.ts
import { Component, EventEmitter, OnInit, Output } from '@angular/core';
import { FormControl, FormGroup, Validators } from '@angular/forms';

@Component({
  selector: 'app-guess-form',
  templateUrl: './guess-form.component.html',
  styleUrls: ['./guess-form.component.css'],
})
export class GuessFormComponent implements OnInit {
  GUESS_LENGTH = 5;
  guessFormGroup = new FormGroup({
    word: new FormControl('', [
      Validators.required,
      Validators.minLength(5),
      Validators.maxLength(5),
    ]),
  });
  @Output() onGuess = new EventEmitter<string>();

  onSubmit() {
    this.onGuess.emit(this.guessFormGroup.value.word.toLowerCase());
    this.guessFormGroup.reset();
  }

  constructor() {}

  ngOnInit(): void {}
}

<!-- TODO: Validate that is in guessable_words.json. -->
<form [formGroup]="guessFormGroup" (ngSubmit)="onSubmit()">
  <input type="text" formControlName="word" />
  <button type="submit" [disabled]="!guessFormGroup.valid">Submit</button>
</form>

// src/GuessForm.tsx
import { useState } from "react";
import { WORD_LENGTH } from "./constants";
import { default as guessableWords } from "./data/guessable_words.json";
import "./GuessForm.css";

export function GuessForm({ onGuess }: { onGuess: (guess: string) => void }) {
  const [guess, setGuess] = useState("");
  return (
    <form
      className="GuessForm"
      onSubmit={(e) => {
        e.preventDefault();
        if (!guessableWords.includes(guess)) {
          return;
        }
        onGuess(guess);
        setGuess("");
      }}
    >
      <input
        type="text"
        value={guess}
        required
        minLength={WORD_LENGTH}
        maxLength={WORD_LENGTH}
        style={{ textTransform: "uppercase" }}
        onChange={(e) => {
          setGuess(e.currentTarget.value.toLowerCase());
        }}
      />
      <button type="submit">Submit</button>
    </form>
  );
}
