// src/app/guess-display/guess-display.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { LetterResult } from 'src/types/LetterResult';
import { Result } from '../../types/Result';
import chain from '@anoop901/js-util/chain';
import map from '@anoop901/js-util/iterables/map';
import toArray from '@anoop901/js-util/iterables/toArray';
import zip from '@anoop901/js-util/iterables/zip';
import { HistoryItem } from 'src/types/HistoryItem';

@Component({
  selector: 'app-guess-display',
  templateUrl: './guess-display.component.html',
  styleUrls: ['./guess-display.component.css'],
})
export class GuessDisplayComponent implements OnInit {
  @Input() history!: HistoryItem[];

  constructor() {}

  ngOnInit(): void {}

  zippedLettersAndResults(
    guess: string,
    result: Result
  ): { letter: string; letterResult: LetterResult }[] {
    return chain(zip(guess, result))
      .then(
        map(({ first, second }) => ({ letter: first, letterResult: second }))
      )
      .then(toArray)
      .end();
  }
}

<div *ngFor="let historyItem of history" class="guess">
  <div
    *ngFor="
      let letterAndResult of zippedLettersAndResults(
        historyItem.guess,
        historyItem.result
      )
    "
    class="letter letter-{{ letterAndResult.letterResult }}"
  >
    {{ letterAndResult.letter }}
  </div>
</div>

// src/GuessDisplay.tsx
import { chain } from "@anoop901/js-util";
import { enumerate, map, toArray, zip } from "@anoop901/js-util/iterables";
import { GameState } from "./types/GameState";
import "./GuessDisplay.css";

export const GuessDisplay = ({ gameState }: { gameState: GameState }) => {
  return (
    <div>
      {gameState.history.map(({ guess, result }, guessIndex) => (
        <div className="guess" key={guessIndex}>
          {chain(zip(guess, result))
            .then(enumerate)
            .then(
              map(
                ({
                  index: letterIndex,
                  value: { first: letter, second: letterResult },
                }) => (
                  <div
                    key={letterIndex}
                    className={`letter letter-${letterResult}`}
                  >
                    {letter}
                  </div>
                )
              )
            )
            .then(toArray)
            .end()}
        </div>
      ))}
    </div>
  );
};
