// src/app/letters-display/letters-display.component.ts
import { Component, EventEmitter, Input, OnInit, Output } from '@angular/core';
import chain from '@anoop901/js-util/chain';
import map from '@anoop901/js-util/iterables/map';
import toArray from '@anoop901/js-util/iterables/toArray';
import zip from '@anoop901/js-util/iterables/zip';
import { HistoryItem } from 'src/types/HistoryItem';

@Component({
  selector: 'app-letters-display',
  templateUrl: './letters-display.component.html',
  styleUrls: ['./letters-display.component.css'],
})
export class LettersDisplayComponent implements OnInit {
  @Input() history!: HistoryItem[];
  @Output() addLetterToGuess = new EventEmitter<string>();
  ALL_LETTERS = [...'abcdefghijklmnopqrstuvwxyz'];

  get lettersWithStatuses() {
    const guesses = this.history.flatMap((historyItem) =>
      chain(zip(historyItem.guess, historyItem.result))
        .then(
          map(({ first, second }) => ({ guessedLetter: first, result: second }))
        )
        .then(toArray)
        .end()
    );
    const guessedLetters = new Set(guesses.map((guess) => guess.guessedLetter));
    const guessedLettersCorrect = new Set(
      guesses
        .filter((guess) => guess.result === 'correct')
        .map((guess) => guess.guessedLetter)
    );
    const guessedLettersMisplaced = new Set(
      guesses
        .filter((guess) => guess.result === 'misplaced')
        .map((guess) => guess.guessedLetter)
    );
    return this.ALL_LETTERS.map((letter) => ({
      letter,
      status: guessedLettersCorrect.has(letter)
        ? 'correct'
        : guessedLettersMisplaced.has(letter)
        ? 'misplaced'
        : !guessedLetters.has(letter)
        ? 'unguessed'
        : 'absent',
    }));
  }

  constructor() {}

  ngOnInit(): void {}
}

<div
  *ngFor="let letterWithStatus of lettersWithStatuses"
  [class]="['letter', 'letter-' + letterWithStatus.status]"
  (click)="addLetterToGuess.emit(letterWithStatus.letter)"
>
  {{ letterWithStatus.letter }}
</div>

// src/LettersDisplay.tsx
import { chain } from "@anoop901/js-util";
import { map, toArray, zip } from "@anoop901/js-util/iterables";
import { ALL_LETTERS } from "./constants";
import { HistoryItem } from "./types/HistoryItem";
import "./LettersDisplay.css";
import classNames from "classnames";

export const LettersDisplay = ({ history }: { history: HistoryItem[] }) => {
  const guesses = history.flatMap((historyItem) =>
    chain(zip(historyItem.guess, historyItem.result))
      .then(
        map(({ first, second }) => ({ guessedLetter: first, result: second }))
      )
      .then(toArray)
      .end()
  );
  const guessedLetters = new Set(guesses.map((guess) => guess.guessedLetter));
  const guessedLettersCorrect = new Set(
    guesses
      .filter((guess) => guess.result === "correct")
      .map((guess) => guess.guessedLetter)
  );
  const guessedLettersMisplaced = new Set(
    guesses
      .filter((guess) => guess.result === "misplaced")
      .map((guess) => guess.guessedLetter)
  );

  return (
    <div className="LetterDisplay">
      {ALL_LETTERS.map((letter) => (
        <div
          className={classNames("letter", {
            "letter-absent":
              guessedLetters.has(letter) &&
              !guessedLettersCorrect.has(letter) &&
              !guessedLettersMisplaced.has(letter),
            "letter-correct": guessedLettersCorrect.has(letter),
            "letter-misplaced": guessedLettersMisplaced.has(letter),
            "letter-unguessed": !guessedLetters.has(letter),
          })}
        >
          {letter}
        </div>
      ))}
    </div>
  );
};
